#pragma once

#define ERROR_STATUS 0
#define SUCCESS_STATUS 1
enum class MessageCode{ ERROR_MESSAGE = 'E', LOGIN = 'L', SIGNUP = 'S', STATISTICS = 'T', LOGOUT='O', CREATE_ROOM = 'C', JOIN_ROOM = 'J', GET_ROOMS = 'G', GET_PLAYERS_IN_ROOM = 'P', CLOSE_ROOM = '~', START_GAME = 'A', GET_ROOM_STATE = '?', LEAVE_ROOM = 'V', LEAVE_GAME = 'M', GET_QUESTION = 'Q', SUBMIT_ANSWER = 'B', GET_GAME_RESULT = 'R'};
enum class LoginStatus{ LOGIN_ERROR = 0, LOGIN_SUCCESS, USER_ALREADY_CONNECTED_ERROR};
enum class SignupStatus{ SIGNUP_ERROR = 0, SIGNUP_SUCCESS, USERNAME_EXIST_ERROR, EMAIL_EXIST_ERROR, INVALID_USERNAME, INVALID_PASSWORD, INVALID_EMAIL, INVALID_PHONE, INVALID_ADDRESS, INVALID_BIRTHDATE };
